blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/ScratchAddons/ScratchAddons/discussions/new
    about: Needs discussion (moved to Discussions)
  - name: â“ Help/questions
    url: https://github.com/ScratchAddons/ScratchAddons/discussions/new
    about: Ask a question (moved to Discussions)
