blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/FlagClicked/FlagClicked/discussions/new
    about: Needs discussion (moved to Discussions)
  - name: â“ Help/questions
    url: https://github.com/FlagClicked/FlagClicked/discussions/new
    about: Ask a question (moved to Discussions)
